version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    container_name: fastapi-backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    container_name: streamlit-frontend
    depends_on:
      - backend
